# Generated by Django 4.2.6 on 2023-11-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Username"
            ),
        ),
    ]
